image: gradle:alpine

stages:
  - build
  - test

variables:
  ENVIRONMENT:
    value: "qa"
    options:
      - "dev"
      - "qa"
    description: "Environment for test execution"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x ./gradlew

build:
  stage: build
  script: 
    - ./gradlew build

test:
  stage: test
  script: 
    - echo "Running API test cases with Serenity-BDD"
    - ./gradlew clean test -Denv=$ENVIRONMENT
    
  artifacts:
    when: always
    name: "Serenity API Report"
    paths:
    - target/site/serenity
    expire_in: 24h
